import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/mode-toggle";
import "toastr/build/toastr.min.css";
import { Github, Gitlab, Linkedin, Mail } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manajemen Keuangan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider >
            <AppSidebar variant="inset" />
            <SidebarInset>
              <div className="flex items-center gap-2 px-4 py-2">
                <SidebarTrigger />
                <ModeToggle />
              </div>
              {children}
              {/* Footer */}
              <footer className="mt-8 px-4 py-4 border-t text-sm text-muted-foreground flex flex-col sm:flex-row justify-between items-center gap-2">
                <span>© {new Date().getFullYear()} Manajemen Keuangan</span>
                <div className="flex gap-4">
                  <a href="https://github.com/fakhrizalmus" target="_blank" rel="noopener noreferrer" className="hover:underline">
                    <Github />
                  </a>
                  <a href="https://www.linkedin.com/in/fakhrizalmustaqim" target="_blank" rel="noopener noreferrer" className="hover:underline">
                    <Linkedin />
                  </a>
                  <a href="https://gitlab.com/fakhrizaluciha" target="_blank" rel="noopener noreferrer" className="hover:underline">
                    <Gitlab />
                  </a>
                  <a href="mailto:rizalmustaqim150@gmail.com" target="_blank" rel="noopener noreferrer" className="hover:underline">
                    <Mail />
                  </a>
                </div>
              </footer>
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
