import "@/lib/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Manajemen Keuangan",
  description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                {children}
            </body>
        </html>
    );
}
